`release-2.1` branch: migrate from net7 to net8
PintaProject/Pinta pull request #763
Opened 2024-04-05 05:51 UTC by nikolaevn

net7 EOL is coming  soon ([May 14, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#lifecycle)).
It looks like we need to release version `2.1.2` that only migrates `2.1.1` from net7 to net8.

2024-04-08 16:48 UTC, cameronwhite requested changes
Thanks for looking at this!
I'm fine with doing a minor release to allow building against .NET 8, but I'd prefer doing the 2.1.2 version bump in a separate commit so that it's easier to review. Could you strip this down to just the .NET 8 changes please?

I think we should also port over the changes from the master branch which fixed issues where the .net6.0 CI build didn't actually build against .NET 6, to ensure that no regressions occur for that configuration (https://github.com/PintaProject/Pinta/pull/565/commits/68b8f07bc20493701e4094fa5afc7c55d6aeb8d1)

2024-04-08 16:48 UTC, cameronwhite commented on configure.ac
> +DOTNET_MINIMUM_VERSION=8.0
I think this breaks building against .NET 6?

2024-04-08 16:48 UTC, cameronwhite commented on configure.ac
> +DOTNET_TARGET_FRAMEWORK=net8.0
Similarly, I think this needs to be `net6.0` since the AX_COMPARE_VERSION switches to net8.0 if the version check succeeds

2024-04-12 04:42 UTC, nikolaevn commented
Fixed as requested.

2024-04-13 14:48 UTC, cameronwhite commented
Looks good, thanks!

2024-04-13 14:48 UTC, merged

2024-04-15 07:23 UTC, dafanasiev commented
@cameronwhite can you assign [Milestone 2.1.2](https://github.com/PintaProject/Pinta/milestone/1) to this issue also?